# Generated by Django 4.2.2 on 2023-06-21 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_token_options_alter_token_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
