# Generated by Django 4.2.2 on 2023-06-23 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_remove_user_last_login_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=None, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=32)),
                ('image_url', models.CharField(default='', max_length=128)),
                ('branch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.branch')),
            ],
            options={
                'verbose_name': 'MenuCategory',
                'verbose_name_plural': 'MenuCategories',
                'db_table': 'menu_category',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, unique=True)),
                ('icon_url', models.CharField(default='', max_length=128)),
                ('average_check', models.IntegerField(default=None, null=True)),
                ('time_open', models.TimeField(default=None, null=True)),
                ('time_close', models.TimeField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('admin', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.admin')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=None, max_length=128, null=True)),
                ('restaurant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'RestaurantImage',
                'verbose_name_plural': 'RestaurantImages',
                'db_table': 'restaurant_image',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=64)),
                ('bottom_price', models.IntegerField(default=None, null=True)),
                ('top_price', models.IntegerField(default=None, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('image_url', models.CharField(default='', max_length=128)),
                ('menu_category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.menucategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='BranchImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default=None, max_length=128, null=True)),
                ('branch', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.branch')),
            ],
            options={
                'verbose_name': 'BranchImage',
                'verbose_name_plural': 'BranchImages',
                'db_table': 'branch_image',
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='restaurant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='branch',
            name='waiters',
            field=models.ManyToManyField(to='account.waiter'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('branch', 'title'), name='unique_branch_title_combination'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('restaurant', 'address'), name='unique_restaurant_address_combination'),
        ),
    ]
