# Generated by Django 4.2.2 on 2023-06-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_url_branchimage_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='icon_path',
            field=models.CharField(default='images/default_icon.jpg', max_length=128),
        ),
    ]
