# Generated by Django 4.2.2 on 2023-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_menucategory_unique_branch_title_combination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='image_path',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='icon_path',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
