# Generated by Django 4.2.2 on 2023-07-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menucategory_image_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
